name = "Norwegien blue"
print(name)
print(name[3])
print(name[4])
print(name[9])
print(name[3])
print(name[6])
print(name[8])

print(name[9])
print(name[-11])
print(name[-10])
print(name[-5])
print(name[-11])
print(name[-8])
print(name[-6])

print()
print(name[3-14])
print(name[4-14])
print(name[9-14])
print(name[3-14])
print(name[6-14])
print(name[8-14])
print()
print(name[10:14])
print(name[:6])
print(name[6:])
print(name[:6] + name[6:])
print(name[:])

print(name[-4:-1])
print(name[-4:12])